import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
import typedocSidebar from './docs/api/typedoc-sidebar';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: 'manual'}],
  typedocSidebar: [
    {
      type: 'category',
      label: 'XR Blocks API',
      link: {
        type: 'doc',
        id: 'api/index',
      },
      items: typedocSidebar.items,
    },
  ],

  templatesSidebar: [
    'templates/Basic',
    'templates/Spatial-UI',
    'templates/Object-Interaction',
    'templates/Spatial-Placement',
    'templates/Stereo',
    'templates/Camera-View',
    'templates/AI-Query',
    'templates/AI-Live-Assistant',
    'templates/Scene-Understanding',
    'templates/XR-Modes',
    'templates/Environment-Physics',
    'templates/Agent-Context',
    'templates/Hand-Gestures',
    'templates/TypeScript-Vite',
    'templates/Simulator-Setup',
  ],

  samplesSidebar: [
    {
      type: 'category',
      label: 'Spatial UI',
      collapsed: false,
      items: ['samples/ModelViewer', 'samples/UI'],
    },
    {
      type: 'category',
      label: 'XR Realism',
      collapsed: false,
      items: [
        'samples/Occlusion',
        'samples/DepthMap',
        'samples/DepthMesh',
        'samples/Reticle',
        'samples/Lighting',
        'samples/3DGS-Walkthrough',
      ],
    },
    {
      type: 'category',
      label: 'Avatar Lab',
      collapsed: false,
      items: [
        'samples/GNM-Head',
        'samples/VRM-Avatar',
        'samples/Lipsync',
        'samples/Face-Mirror',
        'samples/Magic-Window',
        'samples/Netblocks',
      ],
    },
    {
      type: 'category',
      label: 'XR Interaction',
      collapsed: false,
      items: [
        'samples/Head-Gestures',
        'samples/XR-Emoji',
        'samples/Custom-Gestures',
        'samples/RockPaperScissors',
      ],
    },
    {
      type: 'category',
      label: 'AI + XR',
      collapsed: false,
      items: [
        'samples/XR-Poet',
        'samples/Gemini-XRObject',
        'samples/Objects-3D',
        'samples/Language-Detector',
        'samples/Gemini-Icebreakers',
        'samples/Collaborative-Roomcraft',
        'samples/Super-Resolution',
        'samples/Offline-Captions',
      ],
    },
    {
      type: 'category',
      label: 'Advanced Demos',
      collapsed: false,
      items: [
        'samples/Ballpit',
        'samples/BalloonPop',
        'samples/Portals',
        'samples/Paint',
        'samples/Splash',
        'samples/Rain',
        'samples/ScreenWiper',
        'samples/Drone',
        'samples/Math-Tutor',
        'samples/Virtual-Screens',
      ],
    },
  ],
};

export default sidebars;
